CREATE TABLE "users" (
	"id"	UUID NOT NULL,
	"name"	TEXT NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	"verified"	BOOL NOT NULL DEFAULT 0,
	"password"	TEXT NOT NULL,
	"roles"	TEXT NOT NULL DEFAULT '',
	"created_at"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE INDEX users_email_idx ON users (email);