[package]
name = "api_schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
ssr = [
    "dep:sqlx",
]

[dependencies]
serde.workspace = true
sqlx = { workspace = true, optional = true }
